### ISSUE TITLE
IPhone XS not being properly recognized by Android Studio for Flutter App

### ISSUE THREAD

**Issue by timtraversy** [libimobiledevice/ideviceinstaller#101]
Hi, I opened this issue with the Flutter team but the problem might be in this library.

[Here is the issue with more details](
https://github.com/flutter/flutter/issues/22147)

Basically the iPhone XS is not being properly recognized by Android Studio when you plug it into the computer, so I can’t run my Flutter app on it. Instead of the iPhone name I’m getting a long string that looks like command line tools for ideviceinfo. Flutter has us install this library to run Flutter apps on iOS, which is why I suspect the issue is here, but I may have misdiagnosed.

I noticed an issue was opened recently about an iOS bug fix: #100. Maybe that has something to do with this?

**Comment by nikias** [comment]
Fixed by removing the redundant length check for UDID.
