### ISSUE TITLE
ideviceinfo does not work on new UDID formats

### ISSUE THREAD

**Issue by SealviewTW** [libimobiledevice/ideviceinstaller#108]
I am still facing the issued described in #100 for new UDID formats when using ideviceinfo and idevicepair

libimobiledevice HEAD-f37b592_2 is already installed and up-to-date

ideviceinfo -u 00008020-000625E11A84002E
Usage: ideviceinfo [OPTIONS]
Show information about a connected device.

-d, --debug	enable communication debugging
-s, --simple	use a simple connection to avoid auto-pairing with the device
-u, --udid UDID	target specific device by its 40-digit device UDID
-q, --domain NAME	set domain of query to NAME. Default: None
-k, --key NAME	only query key specified by NAME. Default: All keys.
-x, --xml	output information as xml plist instead of key/value pairs
-h, --help	prints usage information

Known domains are:

com.apple.disk_usage
com.apple.disk_usage.factory
com.apple.mobile.battery
com.apple.iqagent
com.apple.purplebuddy
com.apple.PurpleBuddy
com.apple.mobile.chaperone
com.apple.mobile.third_party_termination
com.apple.mobile.lockdownd
com.apple.mobile.lockdown_cache
com.apple.xcode.developerdomain
com.apple.international
com.apple.mobile.data_sync
com.apple.mobile.tethered_sync
com.apple.mobile.mobile_application_usage
com.apple.mobile.backup
com.apple.mobile.nikita
com.apple.mobile.restriction
com.apple.mobile.user_preferences
com.apple.mobile.sync_data_class
com.apple.mobile.software_behavior
com.apple.mobile.iTunes.SQLMusicLibraryPostProcessCommands
com.apple.mobile.iTunes.accessories
com.apple.mobile.internal
com.apple.mobile.wireless_lockdown
com.apple.fairplay
com.apple.iTunes
com.apple.mobile.iTunes.store
com.apple.mobile.iTunes

idevicepair -u 00008020-000625E11A84002E
idevicepair: invalid UDID specified (length != 40)

idevicepair - Manage host pairings with devices and usbmuxd.

Usage: idevicepair [OPTIONS] COMMAND

Where COMMAND is one of:
systembuid print the system buid of the usbmuxd host
hostid print the host id for target device
pair pair device with this host
validate validate if device is paired with this host
unpair unpair device with this host
list list devices paired with this host

The following OPTIONS are accepted:
-d, --debug enable communication debugging
-u, --udid UDID target specific device by its 40-digit device UDID
-h, --help prints usage information

Homepage: http://libimobiledevice.org

Is there something that I am missing?

**Comment by nikias** [comment]
@SealviewTW as you mentioned yourself, your codebase it at commit f37b592788bffcb9a70d211aef8b1f84751114ca which is not the latest... That commit is from March 21, 2018 but the fix for the new style UDIDs was added in commit b34e3435c21d06b3e5a4e7b5246fb6ddb6641a9f on October 1, 2018. So you clearly don't have the latest code.
