### ISSUE TITLE
ideviceinstaller -l easily get stuck on my Mac where Wifi is turned off?

### ISSUE THREAD

**Issue by LittleLydia** [libimobiledevice/ideviceinstaller#120]
when targeted iOS with newer system like iOS 13.1.x and iOS 12.x, ideviceinstaller -l will easily get stuck , add -u uuid, the result is same.

I turned off Wifi when I test this. So what maybe the problem, how could I solve it?

**Comment by gdimitris** [comment]
Same here running `ideviceinstaller -u <udid> -U com.my.app` hangs quite frequently (around 2 out of 7 times). 
@nikias can someone take a lookl?

**Comment by gdimitris** [comment]
Thanks @LittleLydia I will try it today 👍

**Comment by gdimitris** [comment]
Installing the new version fixed the issue for me!
