### ISSUE TITLE
ERROR - install .ipa file IOS 12.4.2

### ISSUE THREAD

**Issue by Hiepars** [libimobiledevice/ideviceinstaller#121]
Hello
I am trying to install .ipa file to my iPhone 5s by using the command:
$ideviceinstaller -r test.ipa

I got this error: "ERROR: Restore failed. Got error "APIInternalError"."
Please help me to fix this error.
Thank you.

**Comment by nikias** [comment]
You need to pass `-i` to install an .ipa. `-a` (archive) and `-r` (restore) operations don't work anymore since iOS 7 and anyway don't get an ipa name as argument but a bundle identifier.
