### ISSUE TITLE
iOS 13.5  entightlments

### ISSUE THREAD

**Issue by demhademha** [libimobiledevice/ideviceinstaller#127]
Hi, it seems that ideviceinstaller needs updating for 13.5 as the entightlements in /private/var have changed.
This prevents ideviceinstaller -i to fail, 
Thanks

**Comment by nikias** [comment]
Hmm not sure what you mean, installing on iOS 14 b3 works just fine with latest ideviceinstaller.

**Comment by demhademha** [comment]
Hi, i get the following error:
Device, ipad 7 gen
iOS version 13.5 
Operating system ubuntu 
$ ideviceinstaller -i unc0ver_5.3.1.ipa
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/unc0ver.app/SC_Info/unc0ver.sinf in archive!
Copying 'unc0ver_5.3.1.ipa' to device... DONE.
Installing 'science.xnu.undecimus'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: TakingInstallLock (20%)
Install: PreflightingApplication (30%)
Install: VerifyingApplication (40%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe800801c: Failed to verify code sign
ature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.qvqIs3/extracted/Payload/unc0ver.app : 0xe800801c (No code sign
ature found.)

**Comment by nikias** [comment]
Well as the error shows the app you try to install is not signed, so obviously the installation fails.

**Comment by demhademha** [comment]
Thanks
