### ISSUE TITLE
ideviceinstaller failed to install app after commit 798601d8ff09d4f80a2fd42119112846ea8f050e

### ISSUE THREAD

**Issue by albertdai** [libimobiledevice/ideviceinstaller#129]
After the commit 798601d8ff09d4f80a2fd42119112846ea8f050e, the ideviceinstall failed to app with the error:
Uploading {Bundle ID} package contents... AFC Write error: 30
Error: wrote only 0 of *****

**Comment by nikias** [comment]
I don't really see any error on my side, are you trying to install via network by any chance?

**Comment by albertdai** [comment]
The device is connected via USB.

I could confirm the `ideviceinstaller` installed by the instructions (`autogen.sh`, `make`) in the doc could work fine.  But the `ideviceinstaller` built by `bazel` could not work. Not sure if it is due to I am using another version of OpenSSL. I will close this bug first since it is not an issue of libimobiledevice or ideviceinstaller.
