### ISSUE TITLE
ideviceinstaller doesn't archive application's container on iOS8.

### ISSUE THREAD

**Issue by sshurick** [libimobiledevice/ideviceinstaller#13]
ideviceinstaller doesn't archive  application's container with Documents/Library folders, like it did on iOS6 & iOS7. On iOS8 the archive contains application's bundle only.

console log contains the following related information:
#######
Oct 23 18:05:26 ip34 syncdefaultsd[230] <Notice>: (Note ) marked "com.me.keyvalueservice" topic as "ignored" on (null)
Oct 23 18:05:27 ip34 kernel[0] <Notice>: flow_divert_token_set (0): Failed to get the key unit from the token: 22
Oct 23 18:05:27 ip34 lockdownd[26] <Error>: Could not set socket option SO_OPPORTUNISTIC: Invalid argument
Oct 23 18:05:28 ip34 syslog_relay[150] <Notice>: syslog_relay found the ASL prompt. Starting...

**Comment by FunkyM** [comment]
Apple knows why they changed this...
Confirming this behavior with iOS 8:
```
installd[40] <Notice>: ... Client specified archive type DocumentsOnly, but we only support ApplicationOnly; ignoring.
```
However, as we can't control the archive process in this regard I don't understand the purpose of this ticket and thus closing it. :)
