### ISSUE TITLE
Unable to install inhouse iPA files on iOS 15 (same app works on iOS 14)

### ISSUE THREAD

**Issue by rpayne381** [libimobiledevice/ideviceinstaller#139]
Anyone have a fix or a pull request for this issue yet? testing on iOS 15 Beta 3

```
14:39:13 installation_proxy.c:203 instproxy_unlock(): Unlocked
14:39:13 installation_proxy.c:353 instproxy_receive_status_loop(): command: Install, error -13, code 0xe8008029, name: ApplicationVerificationFailed, description: "Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.95tGvj/extracted/Payload/MYAPP.app : 0xe8008029 (The code signature version is no longer supported.)"
14:39:13 installation_proxy.c:370 instproxy_receive_status_loop(): ignoring message without Status key:
14:39:13 installation_proxy.c:371 instproxy_receive_status_loop(): printing 558 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Error</key>
        <string>ApplicationVerificationFailed</string>
        <key>ErrorDetail</key>
        <integer>-402620375</integer>
        <key>ErrorDescription</key>
        <string>Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.95tGvj/extracted/Payload/MYAPP.app : 0xe8008029 (The code signature version is no longer supported.)</string>
</dict>
</plist>
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008029: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.95tGvj/extracted/Payload/MYAPP.app : 0xe8008029 (The code signature version is no longer supported.)
14:39:13 installation_proxy.c:192 instproxy_lock(): Locked
14:39:13 installation_proxy.c:427 instproxy_receive_status_loop_thread(): done, cleaning up.
14:39:13 installation_proxy.c:203 instproxy_unlock(): Unlocked
```

**Comment by nikias** [comment]
Well as you can see it clearly tells you the problem: `The code signature version is no longer supported.`
You have to sign it with a newer codesign I guess.

**Comment by Dvtbwa** [comment]
> Anyone have a fix or a pull request for this issue yet? testing on iOS 15 Beta 3
> 
> ```
> 14:39:13 installation_proxy.c:203 instproxy_unlock(): Unlocked
> 14:39:13 installation_proxy.c:353 instproxy_receive_status_loop(): command: Install, error -13, code 0xe8008029, name: ApplicationVerificationFailed, description: "Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.95tGvj/extracted/Payload/MYAPP.app : 0xe8008029 (The code signature version is no longer supported.)"
> 14:39:13 installation_proxy.c:370 instproxy_receive_status_loop(): ignoring message without Status key:
> 14:39:13 installation_proxy.c:371 instproxy_receive_status_loop(): printing 558 bytes plist:
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
>         <key>Error</key>
>         <string>ApplicationVerificationFailed</string>
>         <key>ErrorDetail</key>
>         <integer>-402620375</integer>
>         <key>ErrorDescription</key>
>         <string>Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.95tGvj/extracted/Payload/MYAPP.app : 0xe8008029 (The code signature version is no longer supported.)</string>
> </dict>
> </plist>
> ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008029: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.95tGvj/extracted/Payload/MYAPP.app : 0xe8008029 (The code signature version is no longer supported.)
> 14:39:13 installation_proxy.c:192 instproxy_lock(): Locked
> 14:39:13 installation_proxy.c:427 instproxy_receive_status_loop_thread(): done, cleaning up.
> 14:39:13 installation_proxy.c:203 instproxy_unlock(): Unlocked
> ```

**Comment by nikias** [comment]
As mentioned above the problem is that iOS 15 uses a new hash algorithm (SHA1 was deprecated) so the app has to be re-signed with a newer version of Xcode.
