### ISSUE TITLE
ideviceInstaller not working on OS X Yosemite

### ISSUE THREAD

**Issue by Mehul18292** [libimobiledevice/ideviceinstaller#15]
I am having 2 machines, one with Yosemite and one with mavericks. I have installed ideviceinstaller by using "brew install ideviceinstaller"  and it have beeen installed successfully on both machines. Now i have connected iOS 7 device with each of them, and tried to list all apps on device, install app on device, archieve app. In all cases, it have worked in mavericks perfectly. But for yosemite, it always says "Segmentation fault: 11".

Is there any problem with ideviceinstaller on yosemite?

**Comment by sarfmomin** [comment]
Hi everyone,
I am stuck with this problem, can anyone help me to get out of this,
Here is the log 
dvtcddmac:~ sas$ brew install --HEAD ideviceinstaller
==> Cloning http://git.sukimashita.com/ideviceinstaller.git
Updating /Library/Caches/Homebrew/ideviceinstaller--git
==> Checking out branch master
==> Patching
==> ./autogen.sh
configure.ac:14: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:15: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:74: error: possibly undefined macro: AS_COMPILER_FLAGS
./configure: line 2196: syntax error near unexpected token `dist-bzip2'
./configure: line 2196: `AM_INIT_AUTOMAKE(dist-bzip2 no-dist-gzip check-news)'

READ THIS: http://git.io/brew-troubleshooting

**Comment by jmoody** [comment]
@sarfmomin The owners of this repo do not maintain the brew formula.  You should report this on the homebrew site and/or find the maintainer.  

If it is any consolation, I have been able to consistently build from sources on Yosemite w/ Xcode 6.1.1. 

I have also been able to build with homebrew. :(

**Comment by FunkyM** [comment]
@jmoody  Thanks.
@sarfmomin Yes, the problem you have is most likely related to a broken autoconf installation and/or homebrew setup. Furthermore your problem is not related to the segfault discussed in this ticket.
Closing as it's not an issue with ideviceinstaller.
