### ISSUE TITLE
ideviceinstaller --archive doesn't seem to work?

### ISSUE THREAD

**Issue by rnikander** [libimobiledevice/ideviceinstaller#150]
I'm trying to copy the files for a certain app from my iPad. The help page is unclear on what this `--archive` command does, but it sounds like it will create an archive from the container on device, so I tried...

```
% ideviceinstaller -l                           
CFBundleIdentifier, CFBundleVersion, CFBundleDisplayName
...
com.foo.Foo, "20", "Foo"
...
% ideviceinstaller -a com.foo.Foo                   
ERROR: Archive failed. Got error "UnknownCommand".
```

**Comment by nikias** [comment]
This feature has been abandoned by Apple with iOS 7 and doesn't work anymore. I should reflect this in the documentation/output of the app...

**Comment by nikias** [comment]
Added this with commit b4e7004fdffa64570f0496a033b44d66781f4bc5.
