### ISSUE TITLE
ideviceinstaller.c:1399:46: error: incompatible pointer types passing status_cb

### ISSUE THREAD

**Issue by daqiang430** [libimobiledevice/ideviceinstaller#18]
some argc didn't work on new version of libimobiledevice ,How to do it?

/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
  CC       ideviceinstaller-ideviceinstaller.o
ideviceinstaller.c:1058:49: error: incompatible pointer types passing 'void
      (const char *, plist_t, void *)' to parameter of type 'instproxy_status_cb_t' (aka 'void
      (*)(plist_t, plist_t, void *)') [-Werror,-Wincompatible-pointer-types]
                        instproxy_install(ipc, pkgname, client_opts, status_cb, NULL);
                                                                     ^~~~~~~~~
/usr/local/include/libimobiledevice/installation_proxy.h:234:132: note: passing argument to parameter
      'status_cb' here
  ...client, const char *pkg_path, plist_t client_options, instproxy_status_cb_t status_cb, void *use...
                                                                                 ^
ideviceinstaller.c:1065:49: error: incompatible pointer types passing 'void
      (const char *, plist_t, void *)' to parameter of type 'instproxy_status_cb_t' (aka 'void
      (*)(plist_t, plist_t, void *)') [-Werror,-Wincompatible-pointer-types]
                        instproxy_upgrade(ipc, pkgname, client_opts, status_cb, NULL);
                                                                     ^~~~~~~~~
/usr/local/include/libimobiledevice/installation_proxy.h:262:132: note: passing argument to parameter
      'status_cb' here
  ...client, const char *pkg_path, plist_t client_options, instproxy_status_cb_t status_cb, void *use...
                                                                                 ^
ideviceinstaller.c:1077:41: error: incompatible pointer types passing 'void
      (const char *, plist_t, void *)' to parameter of type 'instproxy_status_cb_t' (aka 'void
      (*)(plist_t, plist_t, void *)') [-Werror,-Wincompatible-pointer-types]
                instproxy_uninstall(ipc, appid, NULL, status_cb, NULL);
                                                      ^~~~~~~~~
/usr/local/include/libimobiledevice/installation_proxy.h:283:131: note: passing argument to parameter
      'status_cb' here
  ...client, const char *appid, plist_t client_options, instproxy_status_cb_t status_cb, void *user_d...
                                                                              ^
ideviceinstaller.c:1253:46: error: incompatible pointer types passing 'void
      (const char *, plist_t, void *)' to parameter of type 'instproxy_status_cb_t' (aka 'void
      (*)(plist_t, plist_t, void *)') [-Werror,-Wincompatible-pointer-types]
                instproxy_archive(ipc, appid, client_opts, status_cb, NULL);
                                                           ^~~~~~~~~
/usr/local/include/libimobiledevice/installation_proxy.h:325:129: note: passing argument to parameter
      'status_cb' here
  ...client, const char *appid, plist_t client_options, instproxy_status_cb_t status_cb, void *user_d...
                                                                              ^
ideviceinstaller.c:1391:39: error: incompatible pointer types passing 'void
      (const char *, plist_t, void *)' to parameter of type 'instproxy_status_cb_t' (aka 'void
      (*)(plist_t, plist_t, void *)') [-Werror,-Wincompatible-pointer-types]
                instproxy_restore(ipc, appid, NULL, status_cb, NULL);
                                                    ^~~~~~~~~
/usr/local/include/libimobiledevice/installation_proxy.h:349:129: note: passing argument to parameter
      'status_cb' here
  ...client, const char *appid, plist_t client_options, instproxy_status_cb_t status_cb, void *user_d...
                                                                              ^
ideviceinstaller.c:1399:46: error: incompatible pointer types passing 'void
      (const char *, plist_t, void *)' to parameter of type 'instproxy_status_cb_t' (aka 'void
      (*)(plist_t, plist_t, void *)') [-Werror,-Wincompatible-pointer-types]
                instproxy_remove_archive(ipc, appid, NULL, status_cb, NULL);
                                                           ^~~~~~~~~
/usr/local/include/libimobiledevice/installation_proxy.h:372:136: note: passing argument to parameter
      'status_cb' here
  ...client, const char *appid, plist_t client_options, instproxy_status_cb_t status_cb, void *user_d...
                                                                              ^
6 errors generated.
make[2]: *** [ideviceinstaller-ideviceinstaller.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by cctile** [comment]
Ran into this when building with libimobiledevice-1.2.0.

Back-rev to libimobiledevice-1.1.7 will work.

**Comment by dickeylth** [comment]
Same problems encounted with libimobiledevice-1.2.0.
Any plan to fix the compatible issue in the next version?

**Comment by FunkyM** [comment]
Just compile the "work" branch. I'll merge and fix it soon.
Of course next ideviceinstaller version will be compatible with libimobiledevice 1.2.0.
The development version and git HEAD has no stability guarantee.

**Comment by 0x4d4746h** [comment]
How to get the app user data? ideviceinstaller -a "com.testin.app" -o docs_only ?, it's not work for me, version 1.2.0, why?

**Comment by 0x4d4746h** [comment]
How to get the app user data? ideviceinstaller -a "com.testin.app" -o docs_only ?, it's not work for me, version 1.2.0, why?

**Comment by 0x4d4746h** [comment]
How to get the app user data? ideviceinstaller -a "com.testin.app" -o docs_only ?, it's not work for me, version 1.2.0, why?

**Comment by programmin1** [comment]
Please reopen this bug - still not working with libimobiledevice 1.2 and I see no "work" branch on Github to grab.

**Comment by FunkyM** [comment]
@0x4d4746h Your question is not related to this ticket, create separate tickets, ask on the mailing list or on IRC instead.
@programmin1 The issue is fixed in git head master and will be available in the next release. Thus no need to reopen.
