### ISSUE TITLE
ideviceinstaller HEAD did not build Logs

### ISSUE THREAD

**Issue by sarfmomin** [libimobiledevice/ideviceinstaller#19]
Hi,
I am trying to install ideviceinstaller using command : 
brew install --HEAD ideviceinstaller 

I am getting error as : 
dvtcddmac:~ sas$ brew install --HEAD ideviceinstaller
==> Cloning http://git.sukimashita.com/ideviceinstaller.git
Updating /Library/Caches/Homebrew/ideviceinstaller--git
==> Checking out branch master
==> Patching
==> ./autogen.sh
configure.ac:14: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:15: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:74: error: possibly undefined macro: AS_COMPILER_FLAGS
./configure: line 2196: syntax error near unexpected token `dist-bzip2'
./configure: line 2196: `AM_INIT_AUTOMAKE(dist-bzip2 no-dist-gzip check-news)'

READ THIS: http://git.io/brew-troubleshooting

Please help...I am stuck with this

**Comment by FunkyM** [comment]
HEAD makes no build guarantee, so yes it breaks!
But you appear to have a problem with missing build tools.
This is not an issue with ideviceinstaller but with your build setup.
