### ISSUE TITLE
CRITICAL: On Mac Ideviceinstaller hangs intermittently,only way to recover is replug the device to USB cable.

### ISSUE THREAD

**Issue by srikanthsadhu** [libimobiledevice/ideviceinstaller#24]
Ideviceinstaller on mac with latest version on YOSEMITE,IOS 8.2 seems to hang and the sys log show this msg below
 com.apple.usbmuxd[17630]: SCEDeviceSocketCallback 0x1006027c0-libusbmuxd/org.libimobiledevice.usbmuxd remote peer closed connection for sce 0x1006027c0.

We are stuck that we cant install our app consistently through idevice. Please fix it.

**Comment by shermanericSF** [comment]
I'm getting this too:
ideviceinstaller -> ../Cellar/ideviceinstaller/1.1.0_1/bin/ideviceinstaller

iPad mini: iOS 8.4
Host:  Yosemite 10.10.4

**Comment by nikias** [comment]
You need to be more precise so we can understand what is happening. How large is the .ipa you are installing? Are you even trying to install or are you performing a different operation? Please run idevicesyslog on another terminal while executing ideviceinstaller. This might at least give a little idea on what's going on.
Can you run ideviceinstaller with debug output? Also it would be better to test with latest git HEAD (i.e. compile from source) to make sure this is an actual problem in the latest code.
On my 10.10.4 it works perfectly with iOS 8.4.

**Comment by shermanericSF** [comment]
Sorry Nikias for the delay.
A brew uninstall and a reinstall seemed to do the trick.
Things are working great.
Thanks!
