### ISSUE TITLE
Compile fail on Windows

### ISSUE THREAD

**Issue by skortela** [libimobiledevice/ideviceinstaller#26]
I tryed to compile on Windows 7 (MinGW), but got some compile errors:

 make  all-recursive
make[1]: Entering directory `/c/projects/OpenSource/ideviceinstaller'
Making all in src
make[2]: Entering directory`/c/projects/OpenSource/ideviceinstaller/src'
  CC     ideviceinstaller-ideviceinstaller.o
ideviceinstaller.c: In function 'idevice_wait_for_command_to_complete':
ideviceinstaller.c:335:18: error: storage size of 'ts' isn't known
  struct timespec ts;
                  ^
ideviceinstaller.c:346:3: error: implicit declaration of function 'nanosleep' [-Werror=imp
licit-function-declaration]
   nanosleep(&ts, NULL);
   ^
ideviceinstaller.c:335:18: error: unused variable 'ts' [-Werror=unused-variable]
  struct timespec ts;
                  ^
ideviceinstaller.c: In function 'afc_upload_file':
ideviceinstaller.c:579:5: error: unknown conversion type character 'z' in format [-Werror=
format=]
     fprintf(stderr, "Error: wrote only %d of %zu\n", total, amount);
     ^
ideviceinstaller.c:579:5: error: too many arguments for format [-Werror=format-extra-args]

ideviceinstaller.c: In function 'main':
ideviceinstaller.c:860:4: error: implicit declaration of function 'asprintf' [-Werror=impl
icit-function-declaration]
    if ((asprintf(&pkgname, "%s/%s", PKG_PATH, basename(ipcc)) > 0) && pkgname) {
    ^
cc1.exe: all warnings being treated as errors
make[2]: **\* [ideviceinstaller-ideviceinstaller.o] Error 1
make[2]: Leaving directory `/c/projects/OpenSource/ideviceinstaller/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/c/projects/OpenSource/ideviceinstaller'
make: **\* [all] Error 2

Could you fix those small compile issues?

**Comment by rcmpayne** [comment]
bump. having the same issue with Windows and msys2. imobiledevice builds just fine
```
# make
make  all-recursive
make[1]: Entering directory '/home/rpayne/github/ideviceinstaller-master'
Making all in src
make[2]: Entering directory '/home/rpayne/github/ideviceinstaller-master/src'
  CC       ideviceinstaller-ideviceinstaller.o
ideviceinstaller.c: In function ‘main’:
ideviceinstaller.c:864:9: error: implicit declaration of function ‘asprintf’ [-Werror=implicit-function-declaration]
    if ((asprintf(&pkgname, "%s/%s", PKG_PATH, basename(ipcc)) > 0) && pkgname) {
         ^~~~~~~~
ideviceinstaller.c:910:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
      while (zfsize < zs.size) {
                    ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:439: ideviceinstaller-ideviceinstaller.o] Error 1
make[2]: Leaving directory '/home/rpayne/github/ideviceinstaller-master/src'
make[1]: *** [Makefile:405: all-recursive] Error 1
make[1]: Leaving directory '/home/rpayne/github/ideviceinstaller-master'
make: *** [Makefile:337: all] Error 2
```

**Comment by rcmpayne** [comment]
found a workaround for now until someone can review. 

1. Go to the ideviceinstaller/src and edit the make file
2. Look for GLOBAL_CFLAGS and remove -Werror flag

 make and make install works fine now. but haven't tested the .exe
