### ISSUE TITLE
idevice_id -l returns wrong UDID

### ISSUE THREAD

**Issue by nabeel-ibrahim** [libimobiledevice/ideviceinstaller#29]
I installed ideviceinstaller using brew install --HEAD ideviceinstaller and I'm getting the wrong UDID returned. I get a list of UDIDs and I only have one device connected.
This is what I get
741c4f9a9c8c43bd5a42ca7c6b193d11f46c4fce
f219c51e1bdb972026c18ace54f4200a2c57ad4c
5ea052a6fd72d004232fd86da7bcec0a138b0472
The first one is the correct UDID.

**Comment by aburgh** [comment]
The others are connecting over wifi. They will appear and disappear frequently.

**Comment by nabeel-ibrahim** [comment]
Oh I see, is there a way to get the UDID of only the device connected via USB?

**Comment by aburgh** [comment]
Not currently. The `usbmuxd` daemon may report the connection type, but `libusbmuxd` doesn't appear to track it.

**Comment by aburgh** [comment]
Actually, my comments only apply to the projects hosted under libimobiledevice github account. You can use `libusb` to get a list of iOS devices, and the UDID is in the serial string.

**Comment by nabeel-ibrahim** [comment]
thanks for the info
