### ISSUE TITLE
a issue about ideviceinstaller archive APP

### ISSUE THREAD

**Issue by RonnieLLL** [libimobiledevice/ideviceinstaller#34]
I use the cmd archive a ipa package! there has a problem,
the -o docs_only cmd is invalid.

ideviceinstaller -a com.tongbu.tuihd.LWC432R5KJ -o docs_only

but the result has no documents!

**Comment by nikias** [comment]
Unfortunately Apple decided to no longer support archiving application "Documents". See device syslog output:
installd[3935] <Notice>: 0x100584000 -[MIApplicationArchiveManager _onQueue_createArchiveForIdentifier:withOptions:forClient:error:]: Client specified archive type DocumentsOnly, but we only support ApplicationOnly; ignoring.

This is not a bug in ideviceinstaller.
