### ISSUE TITLE
archive issues in iOS 9 beta 5

### ISSUE THREAD

**Issue by tbwolfe** [libimobiledevice/ideviceinstaller#35]
In iOS 8.4.1 (non-jb), I am able to install, remove, and archive apps with no issues using ideviceinstaller from an OS X Mavericks box. In iOS 9 beta 5, I can still install and remove, but am having issues with archival. 

```
$ ideviceinstaller -a com.activision.gw3.dimensions -o copy=iphone/
ERROR: Archive failed. Got error "UnknownCommand".
```

Checking idevicesyslog gives the following:
```
Sep  3 16:12:26 IOS9-test-device mobile_installation_proxy[190] <Error>: 0x16e1bb000 handle_connection: Unknown command
```

Is this expected at this point, or do you have any ideas on what may be causing this issue? 

Thanks!

**Comment by nikias** [comment]
Looks like Apple decided to remove this feature.

**Comment by tbwolfe** [comment]
Thanks for the quick response. Since this is the result of Apple removing functionality, and not a bug / error with the script, I'll close out the issue. 

--B

**Comment by Tatsh** [comment]
Could we re-open this? iTunes still grabs IPAs off the device when you backup and tell it to update apps. This has to mean the feature is still there, maybe the command is renamed?
