### ISSUE TITLE
 Archive failed in iOS 9.0.2

### ISSUE THREAD

**Issue by pondahai** [libimobiledevice/ideviceinstaller#36]
all package from home page's tar
ios device: iphone 4s - ios version: 9.0.2
command: 
ideviceinstaller -a [BUNDLE ID] -o copy=. -o remove
result:
ERROR: Archive failed. Got error "UnknownCommand".

**Comment by 0x4d4746h** [comment]
I got this same error for iOS 9.0.2 - iPhone 6s Plus, any one knowns how to fix it?

**Comment by nikias** [comment]
The Archive command has been removed from iOS 9. I didn't verify it yet but I believe that iTunes is grabbing the purchased apps using the AirTraffic service (com.apple.mobile.atc or maybe com.apple.mobile.atc2).

**Comment by 0x4d4746h** [comment]
hi, @nikias, i think there is still a way to get the archive or basic files of IPA standbox(Document, Library, Temp...), just like the functions of tool "iExplorer", it works fine for iOS 9. Do you have any idea to do this ?
![qq20151014-0](https://cloud.githubusercontent.com/assets/918866/10503316/7e521714-7327-11e5-8c6b-3ae49520c4a2.png)

**Comment by nikias** [comment]
This works for apps that have the file sharing feature enabled using the house arrest service with the VendContainer command. For an example see ifuse (usage: ifuse --container APPID MOUNTPOINT).

**Comment by nikias** [comment]
I just realized that iTunes is not copying any apps from my device anymore during synchronization. The feature has been removed but it also looks like there's no replacement for that functionality, sadly.

**Comment by FunkyM** [comment]
As noted, Apple removed this feature. We might have to add some logic to show that to the user though to prevent ticket duplicates...
