### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by kunal-relan** [libimobiledevice/ideviceinstaller#38]
CC       ideviceinstaller-ideviceinstaller.o
ideviceinstaller.c:906:20: error: comparison of integers of different signs: 'off_t' (aka 'long long') and 'zip_uint64_t' (aka 'unsigned long long') [-Werror,-Wsign-compare]
                                        while (zfsize < zs.size) {
                                               ~~~~~~ ^ ~~~~~~~

**Comment by fryck** [comment]
+1

**Comment by nikias** [comment]
Your libzip version is too old. It needs to be at least >= 0.10 to get rid of this warning. This is why I just committed a new libzip >= 0.10 version requirement.

**Comment by maxanastasio** [comment]
+1
Reproduced on ubuntu 15.10 which purportedly ship libzip-dev 1.0.1-0ubuntu1  (passes requirements check)
