### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by renatorodrigues** [libimobiledevice/ideviceinstaller#4]
`ideviceinstaller` keeps returning `Segmentation fault: 11` whenever I try to install an `.ipa` (I've tried on an iPhone and an iPad, both running iOS 7).

Even the simple command `ideviceinstaller -l` gives this error. Sometimes a dialog appears on the device asking me if I want to trust the computer but clicking on 'Trust' doesn't solve the problem.

If I run `idevicepair unpair` and try again, sometimes, the output is `Could not connect to lockdownd. Exiting.` instead of the segmentation one.

I'm on Mavericks (OS X 10.9.2) and to install the tools I did:

```
brew install libimobiledevice
brew install ideviceinstaller
```

![screenshot 2014-03-18 18 01 00](https://f.cloud.github.com/assets/246079/2451551/6dd8672e-aec7-11e3-82a6-4c87195edd6b.png)

**Comment by lishuai0214** [comment]
I meet this problem today, I solve it by reinstall brew, I suggest upgrade your brew or just delete brew and reinstall the newest version, then reinstall ideviceinstaller, hope this help.

**Comment by tvolkert** [comment]
I actually ran into this today and filed https://github.com/libimobiledevice/ideviceinstaller/issues/73, since I'm running against HEAD, so it seems like it may be a new issue.

**Comment by stevenyix** [comment]
i'm experiencing the same issues as @tvolkert.

**Comment by liaogz82** [comment]
I am experiencing the same issue as @tvolkert too

**Comment by k19870203** [comment]
I am experiencing the same issue as @tvolkert too

**Comment by eguptax** [comment]
Hello everyone, Any updates on this issue. I installed libimobiledevice and ideviceinstaller as --HEAD but still getting segmentation fault: 11 code while installing an ipa on the iPhone. Please let me know if anybody has resolved this issue.
