### ISSUE TITLE
ideviceinstaller is not working with iOS 10.0 beta version(Could not connect to lockdownd. Exiting.)

### ISSUE THREAD

**Issue by AbMathur** [libimobiledevice/ideviceinstaller#47]
I am using libimobiledevice in my iOS project. I upgrade my iphone 6sPlus to iOS 10.0 beta version. i fired ideviceinfo command from my mac and get the response : Could not connect to lockdownd, error code -5

Any one know about this error??

when i am trying to install my ipa through ideviceinstaller, there I am having the following error: Could not connect to lockdownd. Exiting.

please let me know if someone know's the solution!

**Comment by michaelgallacher** [comment]
This issue for me began yesterday when I updated to El Capitan 10.11.6.  It's almost certainly related to a security fix in a dependent module.  Try running as 'sudo' and see if that works.  It did for me, but that's clearly just a workaround.

**Comment by michaelgallacher** [comment]
I'm trying to narrow it down.  What versions of Mac OS, Xcode, and iTunes are you running?

**Comment by AbMathur** [comment]
@michaelgallacher Sudo did'nt work for me. I am using El Capitan 10.11 & itunes 12.4.1.6 version.
i dnt think its Mac OS Problem, its something related to libimobiledevice Packges, 

what do you say?

**Comment by michaelgallacher** [comment]
Which version of 10.11? And do you have a non iOS 10 device you could try?

**Comment by jpsim** [comment]
Getting this error with an iOS 9.3 and iOS 8.4 device on El Capitan 10.11.6. Can't test on previous versions of El Capitan at the moment to check if it's a regression.

**Comment by nikias** [comment]
Did you guys compile the latest libimobiledevice code from git? If not, PLEASE do it _before_ reporting an issue. The error is 100% not in ideviceinstaller.

**Comment by jpsim** [comment]
> Did you guys compile the latest libimobiledevice code from git?

Yes. Though I'm not 100% sure I'm doing this right. Here are the commands I ran to compile and install `ideviceinstaller` from the latest sources:

```
mkdir libmobile
cd libmobile
brew update
brew install autoconf automake libtool libxml2 pkg-config libtasn1 openssl
git clone https://github.com/libimobiledevice/libplist.git
cd libplist
./autogen.sh
./configure
make
make install
cd ..
git clone git@github.com:libimobiledevice/libusbmuxd.git
cd libusbmuxd
./autogen.sh
./configure
make
make install
cd ..
git clone git@github.com:libimobiledevice/libimobiledevice.git
cd libimobiledevice
./autogen.sh
./configure
make
make install
cd ..
git clone git@github.com:libimobiledevice/ideviceinstaller.git
cd ideviceinstaller
export CFLAGS="-Wno-error"
./autogen.sh
./configure
make
make install
```

After running that, I get this:

```
$ ideviceinstaller -l -d
Could not connect to lockdownd. Exiting.
```

Here are all the commands and Terminal output for reference: https://gist.github.com/jpsim/b491a20e6f6c2a4dd29f33221a52776d

**Comment by saurik** [comment]
So, there are two issues here, which is why @nikias is getting confused: there is the -5 error (which is what was originally reported by @AbMathur), and then there is a separate error that looks very similar being caused by using newer versions of macOS (as mentioned by @michaelgallacher and which is consistent with the error output from @jpsim). I spent some time tonight working with @conradev (who is actually running the newest version of macOS, unlike myself, who is still on 10.9.5 ;P), and we determined the issue is that `/var/db/lockdown` is now mode 700, and so the code in `userpref_has_pair_record` that mucks around in that folder no longer works. I've provided a patch in the form of a pull request at libimobiledevice/libimobiledevice#350.

**Comment by nikias** [comment]
@saurik thanks for your comment :) The problem is there are tons of reports about something not working and in the end it turns out that people didn't even used the latest code but some precompiled packages. That's why I was asking. Additionally most people don't state on what platform version (or even platform) they are so it's hard to guess what might be causing this.
On another note, even the latest security fixed 10.11.6 still has ```/var/db/lockdown``` in mode 777 which is why the error reported by ideviceinstaller is probably still the -5 SSL error from libimobiledevice.
@jpsim since I assume you're on 10.11.6 based on your previous comments, is your ```/var/db/lockdown``` world rwx?
also, it would be helpful to reconfigure libimobiledevice with ```--enable-debug-code:```
```
./configure --enable-debug-code && make && sudo make install
```
then ideviceinstaller -d will actually show debug output and it will show the actual issue with lockdownd.

**Comment by saurik** [comment]
@nikias Yeah :(. FWIW, after leaving that comment, @conradev tracked down for me a set of comments with the full history of your SSLv3 issue (as I was checking to make certain the GnuTLS code didn't need to be updated for iOS 10), and I now see how that is *also* be correlated to host OS version (as opposed to iOS version, which is what it has often been billed as), and so yeah: it is quite possible that all of the reports on this issue are the same -5 issue. (Hopefully, though, the separate -21 pull request I reported will get merged, though, as I'm running into tons of people on macOS Sierra ;P.)

**Comment by jpsim** [comment]
After building with @saurik's patch from libimobiledevice/libimobiledevice#350, I could run `ideviceinstaller -l` and `ideviceinstaller -U` successfully on my 10.11.6 (15G26a) machine. Note that I had to specify the `CFLAGS="-Wno-error"` env variable to build ideviceinstaller.

Thanks for the help @nikias and for the patch @saurik!

**Comment by nikias** [comment]
Interesting. Can you check the permissions of ```/var/db/lockdown``` just for reference?
```
ls -ld /var/db/lockdown
```
Mine are still 777 after the update.

**Comment by jpsim** [comment]
My permissions are 700 after running the latest version of `ideviceinstaller` (I didn't check prior to running this version):

```
$ ls -ld /var/db/lockdown
drwx------  11 _usbmuxd  _usbmuxd  374 Jul 26 17:01 /var/db/lockdown
$ stat -f '%A' /var/db/lockdown
700
```

**Comment by nikias** [comment]
Heh, there you go. Thanks!

**Comment by michaelgallacher** [comment]
Just FYI, my permissions for lockdown are identical to what @jpsim listed above after I installed 10.11.6 and Xcode 8.0 beta 3.  Not sure which of the two installs did it, but chmod 777 fixed it.  Thx!

**Comment by nikias** [comment]
@michaelgallacher chmod 777 is not the right approach here. Recompile libimobiledevice with the latest code from git.

**Comment by michaelgallacher** [comment]
Well, yeah, but I didn't want to turn this thread into 'why doesn't ideviceinstaller compile on my mac." :)  Thx.

**Comment by rcmpayne** [comment]
Lol thanks. I tired to compile this in mingw but keeps failing for me. I got libimobiledevice working without issue tho

**Comment by AbMathur** [comment]
Hi All,
My ideviceinstaller problem is resolved on ubuntu 14.04, but i am still facing problem on MAC OS 10.11. i read all your comments but could make it through.

I have a Question :- which is the best Source to download a libimobiledevice or ideviceinstaller Packages, Whether from libimobile offical site or from github ?

 i downloaded libimobiledevice package from github & start installing by these commands:
./autogen.sh
	make
	sudo make install

while firing make command , i got this error: 
 In file included from debug.c:36:
../src/idevice.h:30:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[2]: *** [debug.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

what is this error??, How to resolve this issue?
 
 can someone tell me the steps to download these packages??

**Comment by AbMathur** [comment]
i also downloaded packages from home brew, all packages were downloaded successfully but same error were there Could not connect to lockdownd. Exiting.

**Comment by VasilijSviridov** [comment]
Hello everybody.
After upgrade to El Capitan 11.6 I was facing issue with lock downs from ideviceinstaller, after i granted access 777 to  [/var/db/lockdown which was mode 700] all is working!!! 
Thank you so much for fixing this!!!!!

**Comment by ancowestra** [comment]
Thanks "sudo chmod -R 777 /var/db/lockdown/" works after OSX update 10.11.6

**Comment by madusankapremaratne** [comment]
I am on mac OS 10.11.6
Any fixes for,
Making all in common
  CC       debug.lo
In file included from debug.c:36:
../src/idevice.h:30:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[2]: *** [debug.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by myqqai** [comment]
.bash_profile
export PATH=/usr/local/opt/openssl/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/opt/openssl/lib:$LD_LIBRARY_PATH
export CPATH=/usr/local/opt/openssl/include:$LD_LIBRARY_PATH

**Comment by dyang15** [comment]
I'm on OSX 10.11.6 and experiencing the same issue. When trying to install my app on iOS10 device using -ideviceinstaller I'm getting error "Could not connect to lockdown. Exiting".  I do not have this issue with iOS 8 or 9 devices. I tried "sudo chmod -R 777 /var/db/lockdown/" but still not working.

**Comment by michaelgallacher** [comment]
@dyang15 Please try the following: 

```
brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install ideviceinstaller
brew link --overwrite ideviceinstaller

```

**Comment by forcefeeld** [comment]
thank you @michaelgallacher 

I've been trying to run calabash-ios using ideviceinstaller and the new device_agent solution using an iPhone 7 that was recently updated to ios 10.0.2

I have been getting the error message: "**ERROR: Could not connect to lockdownd. Exiting.**" for the past week now trying to figure out, never thought to reinstall ideviceinstaller   Seems to be installing now. thanks again.

**Comment by michaelgallacher** [comment]
The fix is actually in a version of libimobiledevice which is newer than the version ideviceinstaller currently uses.  Please try this:
```
brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install ideviceinstaller
brew link --overwrite ideviceinstaller
```

**Comment by amang-tavant** [comment]
One way is to update the permissions in /var/db/lockdown folder.

The other way I found is to remove and reinstall the ideviceinstaller from the HEAD of branch:
1) brew uninstall ios-webkit-debug-proxy && brew install ios-webkit-debug-proxy
2) brew uninstall libimobiledevice && brew install --HEAD libimobiledevice

**Comment by seenuvlr1** [comment]
hi @michaelgallacher 

i have tried with your below mentioned procedure,

brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install ideviceinstaller
brew link --overwrite ideviceinstaller


but, when i try to install "brew install --HEAD libimobiledevice" i am getting below error

configure: error: 
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

please help me to solve this issue???

**Comment by michaelgallacher** [comment]
Sounds like something is messed up with your brew install.  I would try re-installing brew and checking to see which versions of Python you have installed and on your system path.

**Comment by niyaoyao** [comment]
@michaelgallacher Thank you so much ! It's work for me~~~~
