### ISSUE TITLE
ideviceinstaller fails with "Could not connect to lockdownd. Exiting."

### ISSUE THREAD

**Issue by prezihomework** [libimobiledevice/ideviceinstaller#48]
When I try to use ideviceinstaller, the command fails with the following error message:
"Could not connect to lockdownd. Exiting."

Example commands:
ideviceinstaller -l
ideviceinstaller -i Something.ipa

I have googled more than an hour to find the solution, however nothing worked for me:
- Reinstall ideviceinstaller
- Reinstall libimobiledevice
- Reinstall brew and reinstall again both ideviceinstaller, libimobiledevice

It works only if I use sudo but it's unfortunately not acceptable in my case.

System paramereters:
MacBookPro with 10.11.5 OSX El Capitan
Target devices: iPhone 5, iPad 2

Note:
I have installed both Xcode 7.3.1 and Xcode 8 beta 3 on my computer. And used these commands to switch between them:
sudo xcode-select -switch /Applications/Xcode-beta.app/
sudo xcode-select -switch /Applications/Xcode.app/

**Comment by renatosc** [comment]
same here.

**Comment by linkin-xiao** [comment]
I meet the same problem, and I guess it's the Xcode 8 lead to this, because I installered Xcode 8 yesterday! 
And before that I use ideviceinstaller a lot time!!!

**Comment by zhaohanzhiyou** [comment]
Same here.. Anyone has any clue? I already uninstalled the Xcode Beta but still not working. THX

**Comment by c0gupr2** [comment]
I am also facing same issue, can somebody please help?

**Comment by KorranForce** [comment]
Look here: https://github.com/libimobiledevice/ideviceinstaller/issues/47

**Comment by prezihomework** [comment]
Thanks KorranForce!
This solution worked perfectly:
`sudo chmod -R 777 /var/db/lockdown/`

I am closing this ticket then.

**Comment by mi2pankaj** [comment]
This works Thanks

**Comment by vivekguptaraw** [comment]
This works WOW!

**Comment by vchimev** [comment]
If the suggestion above doesn't do the trick, an alternative would be:
```
brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install --HEAD  ideviceinstaller
brew link --overwrite ideviceinstaller
sudo chmod -R 777 /var/db/lockdown/
```

**Comment by pellet** [comment]
I need to run this chmod command on each reboot, is there a way around this to have the permission ok across boots?

**Comment by pragpatel** [comment]
> If the suggestion above doesn't do the trick, here is an alternative:
> 
> ```
> brew uninstall ideviceinstaller
> brew uninstall libimobiledevice
> brew install --HEAD libimobiledevice
> brew link --overwrite libimobiledevice
> brew install --HEAD  ideviceinstaller
> brew link --overwrite ideviceinstaller
> sudo chmod -R 777 /var/db/lockdown/
> ```

This one really works

**Comment by ankitguptatest** [comment]
Still didn't work on any above options

**Comment by Winning117** [comment]
If the above doesn't work I was able to get it to work by doing the following:

First disconnect all iOS devices then run this:
`brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install --HEAD  ideviceinstaller
brew link --overwrite ideviceinstaller
sudo rm -rf /var/db/lockdown/*`

Plug your iOS device back in and wait for the "Trust" prompt to pop up. Click "Trust" and then run `sudo chmod -R 777 /var/db/lockdown/`. That solved it for me.

Source: https://stackoverflow.com/a/48694852/7487335

**Comment by jiaxw32** [comment]
> If the suggestion above doesn't do the trick, here is an alternative:
> 
> ```
> brew uninstall ideviceinstaller
> brew uninstall libimobiledevice
> brew install --HEAD libimobiledevice
> brew link --overwrite libimobiledevice
> brew install --HEAD  ideviceinstaller
> brew link --overwrite ideviceinstaller
> sudo chmod -R 777 /var/db/lockdown/
> ```

great ! work for me.

**Comment by harrain** [comment]
> If the above doesn't work I was able to get it to work by doing the following:
> 
> First disconnect all iOS devices then run this:
> 
> ```
> brew uninstall libimobiledevice
> brew install --HEAD libimobiledevice
> brew link --overwrite libimobiledevice
> brew install --HEAD  ideviceinstaller
> brew link --overwrite ideviceinstaller
> sudo rm -rf /var/db/lockdown/*
> ```
> 
> Plug your iOS device back in and wait for the "Trust" prompt to pop up. Click "Trust" and then run `sudo chmod -R 777 /var/db/lockdown/`. That solved it for me.
> 
> Source: https://stackoverflow.com/a/48694852/7487335

Excellent! This is working!
