### ISSUE TITLE
Error building ideviceinstaller 

### ISSUE THREAD

**Issue by matteyeux** [libimobiledevice/ideviceinstaller#50]
I'm running Ubuntu 16.04.
Here is the error, when I build libimobiledevice.

`ideviceinstaller.c:910:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
while (zfsize < zs.size) {`

**Comment by shusso** [comment]
There is #43

**Comment by lippenyit** [comment]
Modify 909 line to:
uint64_t zfsize = 0;
This will fix the problem.

**Comment by matteyeux** [comment]
Thanks it built

**Comment by nikias** [comment]
Fixed with #85
