### ISSUE TITLE
ideviceinstaller is not working with iOS 10.1 released version(Could not connect to lockdownd. Exiting.)

### ISSUE THREAD

**Issue by ansonliao** [libimobiledevice/ideviceinstaller#58]
Hi, 
My:
- **Mac OS version**: 10.11.6
- **iPhone model**: iPhone 6 Plus
- **iOS version**: 10.0.1
- **ideviceinstaller**: installed latest version at 22-Sep-2016
- **Xcode version**: 7.3.1

I tried to use `ideviceinstaller` command to install IPA file to my target iPhone, and get a error:

```bash
Could not connect to lockdownd. Exiting.
```

and then I googled and found some solution from ideviceinstall's github issue list, and the solution is changed the privileges of directory `/var/db/lockdown` to `777` by command:

```bash
sudo chmod -R 777 /var/db/lockdown/
```

after the privilege changed command run, I still gets `Could not connect to lockdownd` error message.

and then I tried run ideviceinstaller IPA installation command to a iPhone with iOS 9.3.2, and the installation was succeeded.

could you kindly help to provide some solution to fix ideviceinstaller installation command to iOS 10 released version?

Thanks.

**Comment by baliand** [comment]
Hello ,

I see this issue also. sudo chmod -R 777 /var/db/lockdown/ doesn't work.
So I interested in when ideviceinstaller or what should I do to make ideviceinstaller working.

Thanks

**Comment by mansi1516** [comment]
Same here, ideviceinstaller is not working for me too on iOS 10 with Xcode 8. Please provide the solution to it.
Thanks..

**Comment by mansi1516** [comment]
I found it working, please see the comments mentioned in https://github.com/libimobiledevice/ideviceinstaller/issues/54

**Comment by ansonliao** [comment]
@mansi1516 
It working by the comments from #54,
the full commands are by disconnected any iOS device:

```
brew uninstall ideviceinstaller -g
brew uninstall libimobiledevice -g
brew install --HEAD libimobiledevice -g
brew install ideviceinstaller -g
sudo rm -rf /var/db/lockdown/*
```

thanks @mansi1516, issue will be closed.

**Comment by baliand** [comment]
Hello,

It doesn't help me.
I'm continue to see "Could not connect to lockdownd. Exiting."

**Comment by ansonliao** [comment]
@baliand 
Please uninstall `libimobiledevice` and `ideviceinstall`, then disconnected all iOS device. 

Then install `libimobiledevice` with `--HEAD`, and `ideviceinstaller`, and removed all file of the directory `/var/db/lockdown/`.

Finally, connect your iOS device again, and `Trust` the Mac on your iPhone.

**Comment by baliand** [comment]
Yes, Yes!!!!
Thanks @ansonliao !!!!

What was the problem?

**Comment by ansonliao** [comment]
@baliand 
it doesn't fix your problem?

after removed the files of `/var/db/lockdown/`, try to run `sudo chmod -R 777 /var/db/lockdown/`

**Comment by baliand** [comment]
Now It's working. 

But I don't understood why it wasn't working.

**Comment by ansonliao** [comment]
@baliand 
I think some key points need to care:

1. re-install `libmobiledevice` have to use `--HEAD`.
2. re-install  `libmobiledevice` and `ideviceinstaller`, make sure no iOS device connected.
3. removes files of `/var/db/lockdown/`, it is the itunes sync history file.
4. changed the privilege of `/var/db/lockdown/`.
5. Trust the Mac when connect the iOS device again.

**Comment by ansonliao** [comment]
BTW, it also works on MacOS Sierra + Xcode 8 + iOS 10.0.x

**Comment by baliand** [comment]
Very interesting key points. Before iOS 10 I used ideviceinstaller without problem.
But after update to iOS 10 I started to see issue. I read many article but your steps helped to me.

I haven't update to MacOS Sierra, using OS X 10.11.6. Now I trying to restore my Testing environment.
So I have problem only with appium. Thanks for help!

**Comment by ansonliao** [comment]
@baliand 
you are welcome, I also works with Appium, my skype is `ansonliao@outlook.com`, looking forward  can discuss more about QA skill in Appium with you.

**Comment by JACK529106** [comment]
Hi，i met an issue here, now my MacOS is Sierra, using OS X 10.12.1. everything is good on my iphone5s(ios9.3.5), but on my iphone6 plus(ios10.1), give the error message "ERROR: Could not connect to lockdownd, error code -5" once using ideviceinstaller. i also try the ways above your all mentioned, still get such this wrong code. who can help me? thanks a lot!
