### ISSUE TITLE
can't install .ipa file IOS 10 xCode 8

### ISSUE THREAD

**Issue by baliand** [libimobiledevice/ideviceinstaller#59]
Hello

Please help me
I can't install .ipa file

I'm alway getting:
**ideviceinstaller -d -i $HOME/build/MyApp.ipa**
**WARNING: could not locate iTunesMetadata.plist in archive!**
**WARNING: could not locate Payload/DISH.app/Info.plist in archive!**

before iOS 10 this command worked great 

Thanks

**Comment by kapil0408** [comment]
Hi Baliand,

Could you please tell that how can i implement ideviceinstaller library in mac application not for  using command line.

Any help would be very appreciate.

**Comment by baliand** [comment]
@kapil0408 

Hello

What do you mean under "implement ideviceinstaller library"? 
Build project to .ipa?

**Comment by kapil0408** [comment]
Acutally i am creating a mac application to get ios device inforamtion like deviceName, UDID, gettting list of Installed app on device , safrai cache etc.

I saw about libiMobileDevice library (iFuse, ideviceinstaller, libplist)
https://github.com/libimobiledevice

So is there any way to implement all these library to using in mac aaplication and not using by command line utitlity.

You got my point?

**Comment by baliand** [comment]
@kapil0408 

Hi

Actually if you use xCode you can finde some info from here

**Comment by nikias** [comment]
@baliand those are just warnings. What happens afterwards?
@kapil0408 what kind of question is that. Of course you can implement that stuff with libimobiledevice, that's why this project exists. It doesn't matter if it's a Linux, macOS, or windows application, you can do whatever you want. Look at the code of the files in libimobiledevice/tools to see how to use it. But please don't post these questions on this issue tracker, which is for reporting real issues or bugs.

**Comment by baliand** [comment]
@nikias Actually I have already found problem and fixed it

**Comment by sivaramprasadc** [comment]
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/DISH.app/Info.plist in archive!

Me also getting the same issue. Can you plz share the solution.

**Comment by leonmeijer** [comment]
@nikias What was the solution?

**Comment by BigFoppa** [comment]
@baliand What was the solution?

**Comment by crummy** [comment]
I resolved this with `brew upgrade --HEAD ideviceinstaller`
