### ISSUE TITLE
ideviceinstaller clang error

### ISSUE THREAD

**Issue by babayorgun46** [libimobiledevice/ideviceinstaller#63]
I have a problem with ideviceinstaller

LOG:
`Cli-MacBook:ideviceinstaller clib$ make`
`/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive`
`Making all in src`
`  CCLD     ideviceinstaller`
`clang: error: argument unused during compilation: '-pthread'`
`make[2]: *** [ideviceinstaller] Error 1`
`make[1]: *** [all-recursive] Error 1`
`make: *** [all] Error 2`
`Cli-MacBook:ideviceinstaller clib$ clang --version`
`Apple LLVM version 8.0.0 (clang-800.0.42.1)`
`Target: x86_64-apple-darwin15.6.0`
`Thread model: posix`
`InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`
`Cli-MacBook:ideviceinstaller clib$ `

**Comment by iOSShohrab** [comment]
having same issue with Mac

**Comment by nikias** [comment]
I think this had to do with libimobiledevice depeding on libpthread. I fixed that in libimobiledevice a while ago so this should be fine now.

**Comment by lakedai** [comment]
before run autogen.sh, add '-Wno-unused-command-line-argument' to line 58 in configure.ac
