### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Astrubale** [libimobiledevice/ideviceinstaller#66]
ideviceinstaller.c: In function ‘main’:
ideviceinstaller.c:910:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
      while (zfsize < zs.size) {
                    ^
cc1: all warnings being treated as errors

**Comment by GaikwadPratik** [comment]
@Astrubale Did you get any update on above issue? I'm also getting same error.

**Comment by nikias** [comment]
Fixed with #85
