### ISSUE TITLE
i don't why some errors after make 

### ISSUE THREAD

**Issue by i19870503** [libimobiledevice/ideviceinstaller#7]
$./autogen.sh
libtoolize: putting auxiliary files in `.'.
libtoolize: linking file`./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file`m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file`m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file`m4/lt~obsolete.m4'
configure.ac:13: installing './compile'
configure.ac:15: installing './config.guess'
configure.ac:15: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
src/Makefile.am: installing './depcomp'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libimobiledevice... yes
checking for libimobiledevice100... yes
checking for libimobiledevice110... yes
checking for libimobiledevice112... yes
checking for libimobiledevice115... yes
checking for libplist... yes
checking for libzip... yes
checking for ANSI C header files... (cached) yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for strcasecmp... yes
checking for strdup... yes
checking for strerror... yes
checking for strndup... yes
checking whether lstat is available... yes
checking for supported compiler flags...  -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter -Werror -g
checking whether make supports nested variables... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating man/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

$make
make  all-recursive
make[1]: Entering directory `/home/zluna/Downloads/ios/ideviceinstaller-master'
Making all in src
make[2]: Entering directory`/home/zluna/Downloads/ios/ideviceinstaller-master/src'
  CC       ideviceinstaller-ideviceinstaller.o
ideviceinstaller.c: In function ‘afc_upload_dir’:
ideviceinstaller.c:546:13: error: ignoring return value of ‘readlink’, declared with attribute warn_unused_result [-Werror=unused-result]
     readlink(fpath, target, st.st_size);
             ^
cc1: all warnings being treated as errors
make[2]: **\* [ideviceinstaller-ideviceinstaller.o] Error 1
make[2]: Leaving directory `/home/zluna/Downloads/ios/ideviceinstaller-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/zluna/Downloads/ios/ideviceinstaller-master'
make: **\* [all] Error 2

**Comment by blackcraz** [comment]
ideviceinstaller.c: In function ‘main’:
ideviceinstaller.c:1058:49: error: passing argument 4 of ‘instproxy_install’ from incompatible pointer type [-Werror=incompatible-pointer-types]
    instproxy_install(ipc, pkgname, client_opts, status_cb, NULL);
                                                 ^
In file included from ideviceinstaller.c:45:0:
/usr/include/libimobiledevice/installation_proxy.h:234:19: note: expected ‘instproxy_status_cb_t {aka void (*)(void *, void *, void *)}’ but argument is of type ‘void (*)(const char *, void *, void *)’
 instproxy_error_t instproxy_install(instproxy_client_t client, const char *pkg_path, plist_t client_options, instproxy_status_cb_t status_cb, void *user_data)
                   ^
ideviceinstaller.c:1065:49: error: passing argument 4 of ‘instproxy_upgrade’ from incompatible pointer type [-Werror=incompatible-pointer-types]
    instproxy_upgrade(ipc, pkgname, client_opts, status_cb, NULL);
                                                 ^
In file included from ideviceinstaller.c:45:0:
/usr/include/libimobiledevice/installation_proxy.h:262:19: note: expected ‘instproxy_status_cb_t {aka void (*)(void *, void *, void *)}’ but argument is of type ‘void (*)(const char *, void *, void *)’
 instproxy_error_t instproxy_upgrade(instproxy_client_t client, const char *pkg_path, plist_t client_options, instproxy_status_cb_t status_cb, void *user_data)
                   ^
ideviceinstaller.c:1077:41: error: passing argument 4 of ‘instproxy_uninstall’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   instproxy_uninstall(ipc, appid, NULL, status_cb, NULL);
                                         ^
In file included from ideviceinstaller.c:45:0:
/usr/include/libimobiledevice/installation_proxy.h:283:19: note: expected ‘instproxy_status_cb_t {aka void (*)(void *, void *, void *)}’ but argument is of type ‘void (*)(const char *, void *, void *)’
 instproxy_error_t instproxy_uninstall(instproxy_client_t client, const char *appid, plist_t client_options, instproxy_status_cb_t status_cb, void *user_data);
                   ^
ideviceinstaller.c:1253:46: error: passing argument 4 of ‘instproxy_archive’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   instproxy_archive(ipc, appid, client_opts, status_cb, NULL);
                                              ^
In file included from ideviceinstaller.c:45:0:
/usr/include/libimobiledevice/installation_proxy.h:325:19: note: expected ‘instproxy_status_cb_t {aka void (*)(void *, void *, void *)}’ but argument is of type ‘void (*)(const char *, void *, void *)’
 instproxy_error_t instproxy_archive(instproxy_client_t client, const char *appid, plist_t client_options, instproxy_status_cb_t status_cb, void *user_data);
                   ^
ideviceinstaller.c:1391:39: error: passing argument 4 of ‘instproxy_restore’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   instproxy_restore(ipc, appid, NULL, status_cb, NULL);
                                       ^
In file included from ideviceinstaller.c:45:0:
/usr/include/libimobiledevice/installation_proxy.h:349:19: note: expected ‘instproxy_status_cb_t {aka void (*)(void *, void *, void *)}’ but argument is of type ‘void (*)(const char *, void *, void *)’
 instproxy_error_t instproxy_restore(instproxy_client_t client, const char *appid, plist_t client_options, instproxy_status_cb_t status_cb, void *user_data);
                   ^
ideviceinstaller.c:1399:46: error: passing argument 4 of ‘instproxy_remove_archive’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   instproxy_remove_archive(ipc, appid, NULL, status_cb, NULL);
                                              ^
In file included from ideviceinstaller.c:45:0:
/usr/include/libimobiledevice/installation_proxy.h:372:19: note: expected ‘instproxy_status_cb_t {aka void (*)(void *, void *, void *)}’ but argument is of type ‘void (*)(const char *, void *, void *)’
 instproxy_error_t instproxy_remove_archive(instproxy_client_t client, const char *appid, plist_t client_options, instproxy_status_cb_t status_cb, void *user_d
                   ^
cc1: all warnings being treated as errors
Makefile:448: recipe for target 'ideviceinstaller-ideviceinstaller.o' failed
make[2]: *** [ideviceinstaller-ideviceinstaller.o] Error 1
make[2]: Leaving directory '/home/fareed/Downloads/ideviceinstaller-1.1.0/src'
Makefile:414: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/fareed/Downloads/ideviceinstaller-1.1.0'
Makefile:346: recipe for target 'all' failed
make: *** [all] Error 2

--------------------

I am on Fedora 22 32-bit.. have no luck compiling this package.

**Comment by programmin1** [comment]
I'm on Ubuntu 14.04 and I have latest libimobiledevice, I have compiled ifuse fine, but ideviceinstaller gives me the same error message as Blackcraz's error above, with latest version. Do I have to configure sources it depends on??
