### ISSUE TITLE
iOS 10.3 (beta 4) - Segmentation fault: 11 returned instead of Complete.

### ISSUE THREAD

**Issue by nadavva** [libimobiledevice/ideviceinstaller#70]
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload ********* in archive!
Copying '*********************************' to device... DONE.
Installing 'com.********.****.****'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - TakingInstallLock (20%)
 - PreflightingApplication (30%)
 - InstallingEmbeddedProfile (30%)
 - VerifyingApplication (40%)
 - CreatingContainer (50%)
 - InstallingApplication (60%)
 - PostflightingApplication (70%)
 - SandboxingApplication (80%)
 - GeneratingApplicationMap (90%)
Segmentation fault: 11

**Comment by derekhoops** [comment]
I'm seeing the same error, on beta 5 too.  Any idea what's going on?

**Comment by niyaoyao** [comment]
[1]    643 segmentation fault  ideviceinstaller -i

**Comment by sohgoh** [comment]
Hi. I also encountered the same error. It seems that CFBundleIdentifier returned during installing application from iOS 10.3 beta. It now works by making the following modifications to installation_proxy.c in libimobiledevice.

```
diff --git a/include/libimobiledevice/installation_proxy.h b/include/libimobiledevice/installation_proxy.h
index bc23f9d..e8c69bf 100644
--- a/include/libimobiledevice/installation_proxy.h
+++ b/include/libimobiledevice/installation_proxy.h
@@ -497,6 +497,14 @@ void instproxy_client_options_free(plist_t client_options);
  */
 instproxy_error_t instproxy_client_get_path_for_bundle_identifier(instproxy_client_t client, const char* bundle_id, char** path);

+/**
+ * Gets CFBundleIdentifier of a status.
+ *
+ * @param status The dictionary status response to use.
+ * @param name Pointer to store the name of the status.
+ */
+void instproxy_get_cfbundle_identifier(plist_t status, char **name);
+
 #ifdef __cplusplus
 }
 #endif
diff --git a/src/installation_proxy.c b/src/installation_proxy.c
index 9f367aa..155c34b 100644
--- a/src/installation_proxy.c
+++ b/src/installation_proxy.c
@@ -320,6 +320,7 @@ static instproxy_error_t instproxy_receive_status_loop(instproxy_client_t client
        plist_t node = NULL;
        char* command_name = NULL;
        char* status_name = NULL;
+       char* bundle_identifier = NULL;
        char* error_name = NULL;
        char* error_description = NULL;
        uint64_t error_code = 0;
@@ -363,11 +364,20 @@ static instproxy_error_t instproxy_receive_status_loop(instproxy_client_t client
                        /* check status from response */
                        instproxy_status_get_name(node, &status_name);
                        if (!status_name) {
-                               debug_info("failed to retrieve name from status response with error %d.", res);
-                               complete = 1;
-                       }
-
-                       if (status_name) {
+                               instproxy_get_cfbundle_identifier(node, &bundle_identifier);
+                               free(status_name);
+                               status_name = NULL;
+                               if (!bundle_identifier) {
+                                       debug_info("failed to retrieve name from status response with error %d.", res);
+                                       plist_free(node);
+                                       node = NULL;
+                                       break;
+                               } else {
+                                       free(bundle_identifier);
+                                       bundle_identifier = NULL;
+                                       continue;
+                               }
+                       } else {
                                if (!strcmp(status_name, "Complete")) {
                                        complete = 1;
                                } else {
@@ -869,6 +879,18 @@ LIBIMOBILEDEVICE_API void instproxy_status_get_percent_complete(plist_t status,
        }
 }

+LIBIMOBILEDEVICE_API void instproxy_get_cfbundle_identifier(plist_t status, char **name)
+{
+       if (name) {
+               plist_t node = plist_dict_get_item(status, "CFBundleIdentifier");
+               if (node) {
+                       plist_get_string_val(node, name);
+               } else {
+                       *name = NULL;
+               }
+       }
+}
+
 LIBIMOBILEDEVICE_API void instproxy_status_get_current_list(plist_t status, uint64_t* total, uint64_t* current_index, uint64_t* current_amount, plist_t* list)
 {
        plist_t node = NULL;
```

**Comment by Jun-GitHub** [comment]
I'm also seeing the same error, on iOS 10.3(official version). 

> WARNING: could not locate iTunesMetadata.plist in archive!
> WARNING: could not locate Payload/********************.sinf in archive!
> Copying '********.ipa' to device... DONE.
> Installing 'com.*******'
> Install: CreatingStagingDirectory (5%)
> Install: ExtractingPackage (15%)
> Install: InspectingPackage (20%)
> Install: TakingInstallLock (20%)
> Install: PreflightingApplication (30%)
> Install: InstallingEmbeddedProfile (30%)
> Install: VerifyingApplication (40%)
> Install: CreatingContainer (50%)
> Install: InstallingApplication (60%)
> Install: PostflightingApplication (70%)
> Install: SandboxingApplication (80%)
> Install: GeneratingApplicationMap (90%)
> Segmentation fault: 11

**Comment by niyaoyao** [comment]
@Jun-GitHub I solved this problem by uninstalling and reinstalling homebrew again and again.Finally, it is work unexceptional. Hope this is useful for you. Good luck! : )

**Comment by niyaoyao** [comment]
@Jun-GitHub I solved this problem by uninstalling and reinstalling homebrew again and again.Finally, it is work inexplicable. Hope this is useful for you. Good luck! : )

**Comment by reaniwen** [comment]
@niyaoyao Why would uninstall and reinstall homebrew work? It doesn't make sense.

**Comment by nadzeya** [comment]
I also see this issue after updating one of iPhone devices to 10.3 :(

**Comment by niyaoyao** [comment]
@reaniwen It seems that it's a fault of homebrew.

**Comment by cthinkel** [comment]
The changes suggested by @sohgoh resolved the issue for us.

**Comment by kiltyj** [comment]
This seems to be a bug in ideviceinstaller, not libimobiledevice. Here's the patch we used to get it working without modifications to libimobiledevice:

```diff --git a/src/ideviceinstaller.c b/src/ideviceinstaller.c
index 0f9cc99..8b40bb3 100644
--- a/src/ideviceinstaller.c
+++ b/src/ideviceinstaller.c
@@ -180,7 +180,7 @@ static void status_cb(plist_t command, plist_t status, void *unused)
 					print_apps(current_list);
 					plist_free(current_list);
 				}
-			} else {
+			} else if (status_name) {
 				/* get progress if any */
 				int percent = -1;
 				instproxy_status_get_percent_complete(status, &percent);
```

It seems the code above incorrectly assumed that the status name would be non-null for each status callback. Happy to create a PR, if it helps...

**Comment by reaniwen** [comment]
@kiltyj I don't think this is a good solution since it won't tell you 'success' after installation in 10.3.X.

**Comment by progressnerd** [comment]
Two fixes make this really work.

1. Change installation_proxy.c to remove the following line:
```
if (!status_name) {
	debug_info("failed to retrieve name from status response with error %d.", res);
	complete = 1;
}
```
The installation already quits early when it sees an error. There is no need for it to quit early on a non-error, non-status plist. 

2. The fix to ideviceinstaller.c mentioned above that replaces
`} else {`
with
`} else if (status_name) {`

Together, they ensure the installation does not segfault when receiving the CFBundleIdentifier _and_ let's the installation continue to completion.

**Comment by Jun-GitHub** [comment]
@niyaoyao  your idea isn't solved this problem on my computer,  I just changed the code in my project, when it turn to (90%), return "install success".  thanks any way.

**Comment by jflow** [comment]
Any updates on this? We are compiling manually and without this resolved in the master branch we have to add one of these suggestions. @sohgoh solution works for us, but we are only on macOS.

**Comment by bsansouci** [comment]
I have this issue even when installing through brew with `brew install --HEAD ideviceinstaller`

**Comment by Blefish** [comment]
Fixed with https://github.com/libimobiledevice/ideviceinstaller/commit/f07a9a0a4b844d12f70569ce8ca7c555ddb3cad8 ?

**Comment by nikias** [comment]
Yes @Blefish should be fixed with https://github.com/libimobiledevice/ideviceinstaller/commit/f07a9a0a4b844d12f70569ce8ca7c555ddb3cad8
I am not sure about the change mentioned above in installation_proxy.c though.

**Comment by progressnerd** [comment]
I think you still need the fix to installation_proxy.c, otherwise instproxy_receive_status_loop is going to quit early if it can't get the status name.
