### ISSUE TITLE
Option to stop/kill an app

### ISSUE THREAD

**Issue by vineyyadav** [libimobiledevice/ideviceinstaller#76]
Does ideviceinstaller have a command line option to force stop or kill an app? Something like `idevicedebug stop "bundle id"`.

If not, can this be considered as a feature request?

**Comment by nikias** [comment]
No. First, this only works for debug applications, and second such a feature doesn't fit the usage of the tool, which is installing and uninstalling apps. However note that uninstalling an app will also kill the app ;-)

**Comment by nikias** [comment]
Also when there is alread a tool that does it, why add that feature to another one?

**Comment by vineyyadav** [comment]
@nikias, which tool are you referring to that can be used to kill/stop an app?

**Comment by nikias** [comment]
idevicedebug kills the app when you stop the debug session. Look at the code.
