### ISSUE TITLE
IPA is not install on iOS 11 Developer preview beta version.

### ISSUE THREAD

**Issue by omkarzunjurke** [libimobiledevice/ideviceinstaller#80]
I Download iOS 11 Beta Developer Preview on iPhone 6.
I tried using ideviceinstaller Version 1.0 on Ubuntu & Mac. 
it gives following error:
Could not connect connect to lockdown. Exiting 

I tried by given permission chmod 777 to lockdown but it did not work.
also, ideviceinfo commands not working it gives:
ERROR: Could not connect to lockdown, error code -8
I tired pair, unpair combination but it did n't work.

Please share your experience on ios 11 & also solution over it.

**Comment by nikias** [comment]
See my patch here: https://github.com/libimobiledevice/libimobiledevice/issues/510#issuecomment-307375896
